/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Sistema;

import Controller.TrabajadorController;
import Model.Trabajador.Trabajadores;
import UtilDate.UtilGui;
import View.View;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dering
 */
public class FrmAdministrador extends javax.swing.JFrame implements View<Trabajadores>{

    private TrabajadorController controller;
    private Trabajadores trabajadores;
    private DefaultTableModel tablemodel;
    TableRowSorter<TableModel> sorter;
    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
        controller = new TrabajadorController(this);
        this.setLocationRelativeTo(this);
        tablemodel = (DefaultTableModel) TxtDatos.getModel();
        sorter = new TableRowSorter<>(this.TxtDatos.getModel());
        TxtDatos.setRowSorter(sorter);
        
        TxtDatos.getSelectionModel().addListSelectionListener(evt -> {
        if (!evt.getValueIsAdjusting()) {
            int selectedRow = TxtDatos.getSelectedRow();
            if (selectedRow >= 0) {
                // Obtener los valores de la fila seleccionada
                String cedula = tablemodel.getValueAt(selectedRow, 0).toString();
                String nombre = tablemodel.getValueAt(selectedRow, 1).toString();
                String telefono = tablemodel.getValueAt(selectedRow, 2).toString();
                String correo = tablemodel.getValueAt(selectedRow, 3).toString();
                String puesto = tablemodel.getValueAt(selectedRow, 4).toString();
                String horario = tablemodel.getValueAt(selectedRow, 5).toString();
                double salario = Double.parseDouble(tablemodel.getValueAt(selectedRow, 6).toString());

                // Pasar los valores a los JTextFields y JComboBox
                TxtCedula.setText(cedula);
                TxtNombre.setText(nombre);
                TxtTelefono.setText(telefono);
                TxtCorreo.setText(correo);
                TxtPuesto.setSelectedItem(puesto);
                TxtHorario.setText(horario);
                TxtSalario.setText(String.valueOf(salario));
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        BtnProducción = new javax.swing.JButton();
        BtnTrabajador = new javax.swing.JButton();
        BtnAlmacenamiento = new javax.swing.JButton();
        BtnCultivos1 = new javax.swing.JButton();
        TpContenedor = new javax.swing.JTabbedPane();
        PnTrabajador = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        btnBuscarID = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPuesto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtHorario = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDatos = new javax.swing.JTable();
        PnCultivo = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TxtID2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtDatos2 = new javax.swing.JTable();
        PnProducción = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtID3 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtDatos3 = new javax.swing.JTable();
        PnAlmacenamiento = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtID1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtDatos1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnProducción.setBackground(new java.awt.Color(51, 102, 255));
        BtnProducción.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        BtnProducción.setForeground(new java.awt.Color(255, 255, 255));
        BtnProducción.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Producción.png"))); // NOI18N
        BtnProducción.setText("Producción");
        BtnProducción.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProducción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProducciónActionPerformed(evt);
            }
        });
        Menu.add(BtnProducción, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 200, 50));

        BtnTrabajador.setBackground(new java.awt.Color(51, 102, 255));
        BtnTrabajador.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        BtnTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        BtnTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Agregar.png"))); // NOI18N
        BtnTrabajador.setText("Trabajador");
        BtnTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrabajadorActionPerformed(evt);
            }
        });
        Menu.add(BtnTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 200, 50));

        BtnAlmacenamiento.setBackground(new java.awt.Color(51, 102, 255));
        BtnAlmacenamiento.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        BtnAlmacenamiento.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlmacenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Almacen.png"))); // NOI18N
        BtnAlmacenamiento.setText("Almacenamiento");
        BtnAlmacenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlmacenamientoActionPerformed(evt);
            }
        });
        Menu.add(BtnAlmacenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 200, 50));

        BtnCultivos1.setBackground(new java.awt.Color(51, 102, 255));
        BtnCultivos1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        BtnCultivos1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCultivos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cultivo.png"))); // NOI18N
        BtnCultivos1.setText("Cultivos     ");
        BtnCultivos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCultivos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCultivos1ActionPerformed(evt);
            }
        });
        Menu.add(BtnCultivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 200, 50));

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1080, 70));

        TpContenedor.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        PnTrabajador.setBackground(new java.awt.Color(255, 255, 255));
        PnTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Trabajador");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        TxtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TxtIDMouseReleased(evt);
            }
        });
        TxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDActionPerformed(evt);
            }
        });
        TxtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtIDKeyReleased(evt);
            }
        });
        jPanel3.add(TxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 650, -1));

        btnBuscarID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar.png"))); // NOI18N
        btnBuscarID.setBorder(null);
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xml (2).png"))); // NOI18N
        jButton22.setBorder(null);
        jPanel3.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        PnTrabajador.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Cédula: ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TxtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioActionPerformed(evt);
            }
        });
        jPanel4.add(TxtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Nombre: ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setText("Telefono: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        TxtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCedulaFocusLost(evt);
            }
        });
        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        jPanel4.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 310, -1));

        TxtPuesto.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TxtPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puesto", "Granjero", "Cultivador", "Ayudante Agricola", "Gerente Produccion", " " }));
        TxtPuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TxtPuestoItemStateChanged(evt);
            }
        });
        jPanel4.add(TxtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setText("Correo: ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel4.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Horario: ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });
        jPanel4.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 140, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setText("Salario: ");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        TxtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHorarioActionPerformed(evt);
            }
        });
        jPanel4.add(TxtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 310, -1));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 80));

        btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/expediente.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 80));

        btnActualizar.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actualizar-datos.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 80));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar-el-archivo.png"))); // NOI18N
        jButton6.setBorder(null);
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 80));

        PnTrabajador.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 350));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Telefono", "Correo", "Puesto", "Horario", "Salario"
            }
        ));
        jScrollPane1.setViewportView(TxtDatos);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 330));

        PnTrabajador.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 660, 350));

        TpContenedor.addTab("", PnTrabajador);

        PnCultivo.setBackground(new java.awt.Color(255, 255, 255));
        PnCultivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel16.setText("Cultivos");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel9.add(TxtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 650, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar.png"))); // NOI18N
        jButton12.setBorder(null);
        jPanel9.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xml (2).png"))); // NOI18N
        jButton23.setBorder(null);
        jPanel9.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        PnCultivo.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel17.setText("Codigo: ");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel18.setText("Nombre: ");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel19.setText("Tipo:");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, -1));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 310, -1));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel20.setText("Estado:");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, -1));

        jLabel21.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel21.setText("Siembra:");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 310, -1));

        jLabel22.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        jButton13.setBorder(null);
        jPanel10.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 80));

        jButton14.setBackground(new java.awt.Color(204, 204, 204));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/expediente.png"))); // NOI18N
        jButton14.setBorder(null);
        jPanel10.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 80));

        jButton15.setBackground(new java.awt.Color(204, 204, 204));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actualizar-datos.png"))); // NOI18N
        jButton15.setBorder(null);
        jPanel10.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 80));

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar-el-archivo.png"))); // NOI18N
        jButton16.setBorder(null);
        jPanel10.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 80));

        jLabel23.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel23.setText("Area: ");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel10.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, -1));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 310, -1));

        PnCultivo.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 350));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDatos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Area", "Estado", "Siembra", "Cosecha"
            }
        ));
        jScrollPane3.setViewportView(TxtDatos2);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 330));

        PnCultivo.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 660, 350));

        TpContenedor.addTab("", PnCultivo);

        PnProducción.setBackground(new java.awt.Color(255, 255, 255));
        PnProducción.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Producción");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel12.add(TxtID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 620, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar.png"))); // NOI18N
        jButton17.setBorder(null);
        jPanel12.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xml (2).png"))); // NOI18N
        jButton24.setBorder(null);
        jPanel12.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        PnProducción.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel12.setText("Codigo: ");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel15.setText("Calidad: ");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 300, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, -1));

        jLabel25.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel25.setText("Cantidad: ");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        jButton18.setBorder(null);
        jPanel13.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 80));

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/expediente.png"))); // NOI18N
        jButton19.setBorder(null);
        jPanel13.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 80));

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actualizar-datos.png"))); // NOI18N
        jButton20.setBorder(null);
        jPanel13.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 80));

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar-el-archivo.png"))); // NOI18N
        jButton21.setBorder(null);
        jPanel13.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 80));

        jLabel27.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel27.setText("Fecha: ");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, -1));

        jLabel28.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel28.setText("Destino: ");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 300, -1));

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 300, -1));

        PnProducción.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 350));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDatos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha", "Calidad", "Cantidad", "Destino"
            }
        ));
        jScrollPane4.setViewportView(TxtDatos3);

        jPanel14.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 330));

        PnProducción.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 660, 350));

        TpContenedor.addTab("", PnProducción);

        PnAlmacenamiento.setBackground(new java.awt.Color(255, 255, 255));
        PnAlmacenamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setText("Almacenamiento");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel6.add(TxtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 580, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar.png"))); // NOI18N
        jButton7.setBorder(null);
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/xml (2).png"))); // NOI18N
        jButton25.setBorder(null);
        jPanel6.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, 40));

        PnAlmacenamiento.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDatos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "Ingreso", "Retiro"
            }
        ));
        jScrollPane2.setViewportView(TxtDatos1);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 330));

        PnAlmacenamiento.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 660, 350));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("Codigo: ");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 300, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 300, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setText("Fecha de retiro:  ");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/borrar.png"))); // NOI18N
        jButton8.setBorder(null);
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 80));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/expediente.png"))); // NOI18N
        jButton9.setBorder(null);
        jPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 80));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actualizar-datos.png"))); // NOI18N
        jButton10.setBorder(null);
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 90, 80));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar-el-archivo.png"))); // NOI18N
        jButton11.setBorder(null);
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 80));

        jLabel24.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel24.setText("Fecha de ingreso:  ");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, -1));

        PnAlmacenamiento.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 350));

        TpContenedor.addTab("", PnAlmacenamiento);

        jPanel1.add(TpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1130, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                int startX = Menu.getX();
                int endX = (startX == 0) ? 1080 : 0;
                int deltaX = (startX == 0) ? 1 : -1;
                if (startX == 0) {
                    Menu.setVisible(true);
                }
                for (int x = startX; x != endX; x += deltaX) {
                    Menu.setBounds(x, 60, 1080, 70);
                    try {
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                if (endX == 0) {
                    Menu.setVisible(true);
                }
            }
        }).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnProducciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProducciónActionPerformed
        TpContenedor.setSelectedComponent(PnProducción);
    }//GEN-LAST:event_BtnProducciónActionPerformed

    private void BtnTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrabajadorActionPerformed
        TpContenedor.setSelectedComponent(PnTrabajador);
    }//GEN-LAST:event_BtnTrabajadorActionPerformed

    private void BtnAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlmacenamientoActionPerformed
        TpContenedor.setSelectedComponent(PnAlmacenamiento);
    }//GEN-LAST:event_BtnAlmacenamientoActionPerformed

    private void BtnCultivos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCultivos1ActionPerformed
        TpContenedor.setSelectedComponent(PnCultivo);
    }//GEN-LAST:event_BtnCultivos1ActionPerformed

    private void TxtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalarioActionPerformed

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void TxtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHorarioActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         if (!validateRequired()) {
            JOptionPane.showMessageDialog(this, "Faltan datos requeridos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        String puesto = TxtPuesto.getSelectedItem().toString();
        if ("Puesto".equals(puesto)) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un puesto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            double salario = Double.parseDouble(TxtSalario.getText().trim()); 
            trabajadores = new Trabajadores(
                TxtCedula.getText().trim(), 
                TxtNombre.getText().trim(), 
                TxtTelefono.getText().trim(), 
                TxtCorreo.getText().trim(), 
                puesto, // Usar el puesto validado
                TxtHorario.getText().trim(), 
                salario
            );
            controller.insertTrabajador(trabajadores);
            clear();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El salario debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void TxtPuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TxtPuestoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPuestoItemStateChanged

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        controller.readAll();
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    private void TxtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCedulaFocusLost
        if(!TxtCedula.isEditable()) return;
        String id = TxtCedula.getText();
        if (id.trim().isEmpty()) return;
        if (!controller.validatePK(id)){
             showError("La cedula ingresada ya se encuentra registrada");
             TxtCedula.setText("");
        }
    }//GEN-LAST:event_TxtCedulaFocusLost

    private void TxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDActionPerformed
        
    }//GEN-LAST:event_TxtIDActionPerformed

    private void TxtIDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtIDMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDMouseReleased

    private void TxtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIDKeyReleased
        String search =TxtID.getText();
        if(search.trim().isEmpty()){
            sorter.setRowFilter(null);
        }else{
            sorter.setRowFilter(RowFilter.regexFilter("(?i)"+search));
        }
    }//GEN-LAST:event_TxtIDKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    if (!validateRequired()) {
        JOptionPane.showMessageDialog(this, "Faltan datos requeridos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double salario = Double.parseDouble(TxtSalario.getText().trim());
        Trabajadores trabajadorActualizado = new Trabajadores(
            TxtCedula.getText().trim(), 
            TxtNombre.getText().trim(), 
            TxtTelefono.getText().trim(),
            TxtCorreo.getText().trim(),
            TxtPuesto.getSelectedItem().toString(),
            TxtHorario.getText().trim(),
            salario
        );
        controller.update(trabajadorActualizado);
        clear();
        // Actualizar la tabla con los nuevos datos
        controller.readAll();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El salario debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    String cedula = TxtCedula.getText().trim();
    if (cedula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un trabajador para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(  this,"¿Está seguro de que desea eliminar al trabajador con cédula: " + cedula + "?","Confirmar eliminación",JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return; 
    }
    try {
        Trabajadores trabajadorAEliminar = new Trabajadores();
        trabajadorAEliminar.setCedula(cedula);
        controller.delete(trabajadorAEliminar);
        clear();
        controller.readAll();
        JOptionPane.showMessageDialog(this, "Trabajador eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el trabajador: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlmacenamiento;
    private javax.swing.JButton BtnCultivos1;
    private javax.swing.JButton BtnProducción;
    private javax.swing.JButton BtnTrabajador;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PnAlmacenamiento;
    private javax.swing.JPanel PnCultivo;
    private javax.swing.JPanel PnProducción;
    private javax.swing.JPanel PnTrabajador;
    private javax.swing.JTabbedPane TpContenedor;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTable TxtDatos;
    private javax.swing.JTable TxtDatos1;
    private javax.swing.JTable TxtDatos2;
    private javax.swing.JTable TxtDatos3;
    private javax.swing.JTextField TxtHorario;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtID1;
    private javax.swing.JTextField TxtID2;
    private javax.swing.JTextField TxtID3;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JComboBox<String> TxtPuesto;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showAll(List<Trabajadores> ents) {
        
        if(ents==null || tablemodel == null)return;
        tablemodel.setNumRows(0);
        ents.forEach(trabajadores->tablemodel.addRow(
                new Object[]{
                    trabajadores.getCedula(),
                    trabajadores.getNombre(),
                    trabajadores.getTelefono(),
                    trabajadores.getCorreo(),
                    trabajadores.getPuesto(),
                    trabajadores.getHorario(),
                    trabajadores.getSalario()
                    
                }
        ));
    }

    @Override
    public void showMessage(String msg) {
    JOptionPane.showMessageDialog(this, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);

    }

    @Override
    public void showSuccess(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void showError(String err) {
        JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean validateRequired() {
        return UtilGui.validateFields(TxtCedula,TxtNombre,TxtTelefono,TxtCorreo,TxtPuesto,TxtHorario,TxtSalario);
    }

    @Override
    public void show(Trabajadores ent) {
        trabajadores=ent;
        if (ent==null) {
            clear();
            return;
        }
        TxtCedula.setText(ent.getCedula());
        TxtNombre.setText(ent.getNombre());
        TxtTelefono.setText(ent.getTelefono());
        TxtPuesto.setToolTipText(ent.getPuesto());
        TxtCorreo.setText(ent.getCorreo());
        TxtHorario.setText(ent.getHorario());
        TxtSalario.setText(String.valueOf(ent.getSalario()));
    }
    private void clear(){
        UtilGui.clearTxts(
                TxtCedula,
                TxtNombre,
                TxtTelefono,
                TxtCorreo,
                TxtPuesto,
                TxtHorario,
                TxtSalario
        );
    }
    
}
