/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Login.FrmLoginA;
import View.Login.FrmLoginT;

/**
 *
 * @author Dering
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Trabajador = new javax.swing.JButton();
        Admin = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/linea-diagonal.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/linea-diagonal.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 130, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/linea-diagonal.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 220, 180));

        Trabajador.setBackground(new java.awt.Color(102, 255, 102));
        Trabajador.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Trabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/farmer_560168 (2).png"))); // NOI18N
        Trabajador.setText("Trabajador");
        Trabajador.setBorder(null);
        Trabajador.setContentAreaFilled(false);
        Trabajador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Trabajador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/farmer_560168 (2).png"))); // NOI18N
        Trabajador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/farmer_560168.png"))); // NOI18N
        Trabajador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrabajadorActionPerformed(evt);
            }
        });
        jPanel1.add(Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 310, 300));

        Admin.setBackground(new java.awt.Color(102, 255, 102));
        Admin.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hombre-de-negocios (1).png"))); // NOI18N
        Admin.setText("Administrador");
        Admin.setBorder(null);
        Admin.setContentAreaFilled(false);
        Admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Admin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hombre-de-negocios (1).png"))); // NOI18N
        Admin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hombre-de-negocios (2).png"))); // NOI18N
        Admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 310, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        this.setVisible(false);
        FrmLoginA frm = new FrmLoginA();
        frm.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrabajadorActionPerformed
        this.setVisible(false);
        FrmLoginT frm = new FrmLoginT();
        frm.setVisible(true);
    }//GEN-LAST:event_TrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Trabajador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
